import sqlmodel
"""modified token expiration

Revision ID: 06abe46f5130
Revises: e1549b8c2bde
Create Date: 2026-01-04 15:53:41.802366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06abe46f5130'
down_revision: Union[str, Sequence[str], None] = 'e1549b8c2bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('expires_at', sa.DateTime(), nullable=False))
    op.drop_column('token', 'expires_in_seconds')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('expires_in_seconds', sa.INTEGER(), nullable=False))
    op.drop_column('token', 'expires_at')
    # ### end Alembic commands ###
